services:
  mysql:
    image: mysql:latest
    container_name: catastrophe_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: catastrophe
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the script
      
volumes:
  mysql_data:
